services:
  app:
    build: .
    container_name: php_app_fresh
    ports:
      - "8200:80"       # changed port
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: fresh_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: newrootpass   # changed root password
      MYSQL_DATABASE: mydatabase         # changed database name
      MYSQL_USER: newuser                # changed username
      MYSQL_PASSWORD: newpass            # changed user password
    ports:
      - "3333:3306"       # changed port
    volumes:
     - db_data_new:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fresh_pma_panel
    restart: always
    ports:
      - "8201:80"          # changed port
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: newrootpass
    depends_on:
      - db

volumes:
   db_data_new:
